### ISSUE TITLE
Image slider doesn't work in dittany and dragon tree

### ISSUE THREAD

**Issue by LeibCelnik** [JSTOR-Labs/juncture#16]
Dittany paragraph 7 uses a slider in labs site, but images are separate on Juncture. Also applies to dragon tree paragraph 3

<img width="1280" alt="Screen Shot 2021-05-20 at 3 12 28 PM" src="https://user-images.githubusercontent.com/56889280/119039602-71bc8780-b982-11eb-8815-89cf694e5c8f.png">
<img width="1280" alt="Screen Shot 2021-05-20 at 3 12 39 PM" src="https://user-images.githubusercontent.com/56889280/119039610-75e8a500-b982-11eb-9f79-d9e98c7b3b67.png">

**Comment by rsnyder** [comment]
Changed `ve-image curtain` tags to `ve-compare`
