### ISSUE TITLE
Javascript error causing map center to fail

### ISSUE THREAD

**Issue by rsnyder** [JSTOR-Labs/juncture#28]
First paragraph in *Freedom From Scurvy* section in [Arbor vitae](https://juncture-digital.org/jstor-labs/plant-humanities/arbor_vitae/)

**Comment by julia-ha** [comment]
Possibly the same issue in Dragon Tree with paragraph that starts with: "European understandings of the dragon tree evolved as scientific botany developed from the late medieval..."

**Comment by julia-ha** [comment]
Same error shown in Sunflower essay, second paragraph in the "Mythic Encounters and Scientific Debates" section.
